采用语言: 中文
模型: qwen3
项目名称: 面向电磁域多模态信息的任务理解及思维推理技术
领域:
  - 电磁学
  - 人工智能
  - 信号处理
技术需求:
  - 支持文本类、图像类、电磁信号类、频谱图类、时序波形类等不少于5种电磁域典型模态作为输入
  - 具备长时思维链推理能力，推理Token长度不低于2K，支持多轮回溯修正
  - 面向"收集可用电磁数据、理解复杂任务需求、融合多模态信息、生成分析报告"为代表的典型电磁应用任务，实现理解任务需求和长时思维推理的正确率不低于90%
  - 单轮对>4个工具的调用准确率不低于90%，多轮工具调用准确率不低于80%，工具调用错误时具备自我修正能力
  - 支持电磁域专业术语库动态更新，术语识别准确率不低于95%
成果形式: 技术研究报告2份、模型(含源码)1套、仿真训练与验证系统1套、发表SCIEI检索论文2篇
研究周期: 2年
预算: 300000元
参考文献: []
格式: structure/international_structure.md
创新点: "提出一种基于多模态融合与认知推理的电磁任务理解新框架，实现对复杂电磁环境的高效感知与智能决策。"
情景: ""
单章字数: 1000 # 调整为适中值
输出路径: output
最大迭代次数: 3 # 新增：控制作者-编辑的循环次数
